// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNtNZCq9zyqn2BlJccWfOlvI1oYdZQ74U',
    appId: '1:290085303417:web:86f17643ba680057c090a8',
    messagingSenderId: '290085303417',
    projectId: 'wicaraplusapp',
    authDomain: 'wicaraplusapp.firebaseapp.com',
    storageBucket: 'wicaraplusapp.firebasestorage.app',
    measurementId: 'G-D3PTN60L67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoJ5U9pf03ajTC6ywjS5_6a0lCMhCb4LE',
    appId: '1:290085303417:android:7bd74b00fce46516c090a8',
    messagingSenderId: '290085303417',
    projectId: 'wicaraplusapp',
    storageBucket: 'wicaraplusapp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgoXKWEMvT9P2dc9fryxSNEUK0AI3Z0Eo',
    appId: '1:290085303417:ios:403a013f83be3ce0c090a8',
    messagingSenderId: '290085303417',
    projectId: 'wicaraplusapp',
    storageBucket: 'wicaraplusapp.firebasestorage.app',
    iosClientId: '290085303417-aagnbh015bjdpci4j7ccjthh8g0lk8vi.apps.googleusercontent.com',
    iosBundleId: 'com.spesialkaryamandiri.wicaraplusapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgoXKWEMvT9P2dc9fryxSNEUK0AI3Z0Eo',
    appId: '1:290085303417:ios:403a013f83be3ce0c090a8',
    messagingSenderId: '290085303417',
    projectId: 'wicaraplusapp',
    storageBucket: 'wicaraplusapp.firebasestorage.app',
    iosClientId: '290085303417-aagnbh015bjdpci4j7ccjthh8g0lk8vi.apps.googleusercontent.com',
    iosBundleId: 'com.spesialkaryamandiri.wicaraplusapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNtNZCq9zyqn2BlJccWfOlvI1oYdZQ74U',
    appId: '1:290085303417:web:bedd7bbc90e91593c090a8',
    messagingSenderId: '290085303417',
    projectId: 'wicaraplusapp',
    authDomain: 'wicaraplusapp.firebaseapp.com',
    storageBucket: 'wicaraplusapp.firebasestorage.app',
    measurementId: 'G-LHPQZ3HYWF',
  );
}
